### ISSUE TITLE
fam 41- incorrect sample number

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#112]
now I can access  to fam 4, but the sample IDs in the "GT call" window are incorrect. The pedegree fig is also at some extend incorrect even if the 2 sample ID are correct.

Michela

**Comment by moonso** [comment]
Ok is it family 4 or 41?
We eill look into this.

**Comment by 4WGH** [comment]
41,
MichelaMichela Barbaro, M.Sc, PhDSjukhuskemistCentrum f�r Medf�dda Metabola Sjukdomar (CMMS)L7:05Karolinska Universitetssjukhuset Solna17176 Stockholm-----M�ns Magnusson <notifications@github.com> skrev: ----- 

Till: Clinical-Genomics/scout <scout@noreply.github.com>Fr�n: M�ns Magnusson <notifications@github.com>Datum: 2015-05-21 09.15Kopia: 4WGH <michela.barbaro@karolinska.se>�rende: Re: [scout] fam 41- incorrect sample number (#112)
Ok is it family 4 or 41?We eill look into this.

**Comment by robinandeer** [comment]
We will reload cases to resolve other issue and make sure that the correct ids are updated for this case as well

**Comment by 4WGH** [comment]
Hi, we have noticed that several families have the wrong ID number. It seams that it is a general bug? Do you know when this issue will be solved and how would we know that the family is reloaded?
Michela

**Comment by robinandeer** [comment]
I hope that a number of these issues were resolved as of yesterday - I will update and fix the last few cases with incorrect ids today :smiley:

**Comment by 4WGH** [comment]
Great! thankS!
MichelaMichela Barbaro, M.Sc, PhDSjukhuskemistCentrum f�r Medf�dda Metabola Sjukdomar (CMMS)L7:05Karolinska Universitetssjukhuset Solna17176 Stockholm-----Robin Andeer <notifications@github.com> skrev: ----- 

Till: Clinical-Genomics/scout <scout@noreply.github.com>Fr�n: Robin Andeer <notifications@github.com>Datum: 2015-05-26 12.36Kopia: 4WGH <michela.barbaro@karolinska.se>�rende: Re: [scout] fam 41- incorrect sample number (#112)
I hope that a number of these issues were resolved as of yesterday - I will update and fix the last few cases with incorrect ids today

**Comment by robinandeer** [comment]
I've not fixed all the wrong ids - please let me know if any problems persist!
