### ISSUE TITLE
order sanger function not working 

### ISSUE THREAD

**Issue by genecracker** [Clinical-Genomics/scout#1503]
I tried to order sanger from a case in scout and I get an _Internal Server Error_ message.

**Comment by dnil** [comment]
```
2019-11-13 12:55:27,969 - scout.server.app - ERROR: Exception on /cust004/919701400153fam/28f974f4883ef13a680e656e4e26b7d8/snv/True [POST] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variant/views.py", line 233, in verify
   url_builder=url_for
TypeError: variant_verification() got an unexpected keyword argument 'variant_obj' ```

I have a slight feeling that relates to last nights bug fixes, but let's investigate. Thank you for the report!

**Comment by genecracker** [comment]
I had the problem yesterday as well!

**Comment by moonso** [comment]
I have fixed that in https://github.com/Clinical-Genomics/scout/pull/1504

**Comment by dnil** [comment]
😄 Sure, but not just now - might have to be the evening project or for early tomorrow. On the face of it, it looks sort of straightforward I guess, but much like the partial fix yesterday showed, there might be more hiding after that.

**Comment by dnil** [comment]
Thanks @northwestwitch!

**Comment by genecracker** [comment]
I still have the same problem. the fix is not urgent, I can talk to my colleague and ask for Sanger verification :-)

**Comment by dnil** [comment]
Perfect! It will be fixed in release 4.8.3 - unless you have tested it locally, just wait and it will be out soon-ish.
