### ISSUE TITLE
_is_managed check doesn't work for hg38 and cancer snvs?

### ISSUE THREAD

**Issue by molucorner** [Clinical-Genomics/scout#5646]
Thank you for taking the time to contribute an issue!

**⚠️ Important:** Please avoid sharing any sensitive or personal information, including text or images, in this issue.

**Describe the bug**
It seems the is_managed call from _load_variants is missing genome build, so that it always defaults to 37. As the build is part of the id, that seems problematic?

Also, there seems to be problem with cancer snvs, too. When variants are loaded the _is_managed function gets a category that is simply "cancer" for cancer snvs, even though the managed categories variable says it's supposed to be "cancer_snv" (and which it is when exporting managed variants or adding them through the form). Although I did notice that the documentation says to use "cancer" as category when uploading a file with managed variants, which actually would match the check as written.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by northwestwitch** [comment]
Looks like a bug. Thanks for reporting, we'll fix it ASAP!

**Comment by dnil** [comment]
Quite, thank you @molucorner. I'm always perplexed how these things sneak by, given that we actually do test things. But yes, this simply can't work.

As for builds, we so far only really support one build per instance for the managed variants, see e.g. https://github.com/Clinical-Genomics/scout/issues/2498. But it is not pretty as it is, given that there is partial support for build already, it kind of looks like it should work to have both in the same. As we are starting a collection of 38 variants for the LRS now, it would be a very good time to actually fix it. I might not call that part a bug as such, but it is a well known defect that clearly should be fixed.

**Comment by dnil** [comment]
Ok, turns out part of the reason we haven't found the issue is we are not really using this for the somatic side locally. This is a relief at least, meaning at least we have full flexibility changing it later without having to rework the database. How about Lund @ViktorHy or @Jakob37 perhaps? Are you carrying some managed "cancer_snv" variants at the moment?

**Comment by Jakob37** [comment]
> Ok, turns out part of the reason we haven't found the issue is we are not really using this for the somatic side locally. This is a relief at least, meaning at least we have full flexibility changing it later without having to rework the database. How about Lund [@ViktorHy](https://github.com/ViktorHy) or [@Jakob37](https://github.com/Jakob37) perhaps? Are you carrying some managed "cancer_snv" variants at the moment?

I'll double check with Viktor, but from what I can see we only have category "snv" managed variants, no "cancer_snv". We only use Scout for constitutional samples in Lund so I guess that makes sense.

**Comment by northwestwitch** [comment]
This issue is closed but we didn't solve the build38 issue, right? Re-opening!

**Comment by dnil** [comment]
Well, build is still messy, but not bugged with current main. The matching is fixed (now with positional `variant_id` instead, which is build less 🙄, instead of `managed_variant_id` which itself is build aware, although functions for it always default to `build="37"`). We have at least https://github.com/Clinical-Genomics/scout/issues/2498 if not more about refactoring managed_variants, in particular enabling build and possibly owner.

**Comment by northwestwitch** [comment]
> Well, build is still messy, but not bugged with current main. The matching is fixed (now with positional `variant_id` instead, which is build less 🙄, instead of `managed_variant_id` which itself is build aware, although functions for it always default to `build="37"`). We have at least [#2498](https://github.com/Clinical-Genomics/scout/issues/2498) if not more about refactoring managed_variants, in particular enabling build and possibly owner.

Ah OK, re-closing!
