### ISSUE TITLE
mtDNA variant presentation in Scout

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#737]
Sorry for not being clear in my first issue (#731). I wrote transcripts but meant genes in this case. MtDNA only has one "transcript" despite all genes.

All cases, analyzed after you fixed the problem with the missing mtDNA variants, are now presented really strange in Scout. 

Since mtDNA only has one transcript all variants have earlier only been showed connected to one gene. Not all other upstream or downstream genes, since this means all other genes in mtDNA are there. If  they are all there it is impossible to see the important information.

I have attached a pdf with screenshots and more information. Could you please check this out. We need to solve this as soon as possible. Thanks!

[Issue mtDNA in Scout.pdf](https://github.com/Clinical-Genomics/scout/files/1723810/Issue.mtDNA.in.Scout.pdf)

/Helene

**Comment by moonso** [comment]
Hmm ok I understand that it is a problem, it is hard to see anything there. This is also a MIP issue since scout displays what MIP is annotating. We need to discuss with @henrikstranneheim how to solve this and if it should be solved in MIP or Scout.

**Comment by henrikstranneheim** [comment]
It is odd. It has to do with VEP and a specific setting for MT. We have not (should not) have touched this for quite some time. I will have a look

**Comment by henrikstranneheim** [comment]
The problem was a VEP plugin had been overwritten due to a bad way of using curl in the production setting. I have restored the plugin and tested it and now it seems to work well. **NOTE:** Analyses that has passed the VEP step, but is still not uploaded into scout will still have too inclusive annotations, but all analyses prior to VEP but already started will benefit from the change.
